# Generated by Django 4.2.29 on 2026-04-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0008_analysisjob_game_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turningpoint',
            options={'ordering': ['-archive_year', '-archive_month', '-game__played_at']},
        ),
    ]
